<?php get_header(); $products = minikids_products(); ?>
<main>
  <section class="hero"><div class="container hero-grid"><div class="hero-copy"><span class="eyebrow">La diversión empieza aquí</span><h1>Juega, imagina y <em>sonríe.</em></h1><p>Descubre juguetes que despiertan la curiosidad y convierten cada día en una nueva aventura.</p><a class="button" href="#destacados">Ver juguetes <span>→</span></a></div><div class="hero-art"><div class="toy-illustration"><span class="spark one">✦</span><span class="spark two">✦</span><div class="toy-star">★</div><div class="toy-bear"><div class="bear-face"></div><div class="scarf"></div></div></div></div></div></section>
  <div class="container"><div class="trust-row"><div class="trust-item"><span class="trust-icon">🚚</span><span>Envíos a todo<br>el Perú</span></div><div class="trust-item"><span class="trust-icon">🎁</span><span>Regalos para<br>cada ocasión</span></div><div class="trust-item"><span class="trust-icon">🔒</span><span>Compra<br>segura</span></div><div class="trust-item"><span class="trust-icon">💬</span><span>Estamos para<br>ayudarte</span></div></div></div>
  <section class="section"><div class="container"><div class="section-head"><div><h2 class="section-title">Compra por categoría</h2><p class="section-subtitle">Todo lo que necesitas para llenar sus días de diversión.</p></div><a class="text-link" href="#destacados">Ver todo →</a></div><div class="category-grid"><a class="category-card" href="?categoria=peluches"><h3>Peluches</h3><span class="emoji">🧸</span></a><a class="category-card" href="?categoria=didacticos"><h3>Aprende jugando</h3><span class="emoji">🧩</span></a><a class="category-card" href="?categoria=juegos-familiares"><h3>Para compartir</h3><span class="emoji">🎲</span></a><a class="category-card" href="?categoria=vehiculos"><h3>Mini aventuras</h3><span class="emoji">🚀</span></a></div></div></section>
  <section class="section" id="destacados"><div class="container"><div class="section-head"><div><h2 class="section-title">Favoritos de la semana</h2><p class="section-subtitle">Los juguetes que todos quieren llevar a casa.</p></div><a class="text-link" href="?categoria=lo-nuevo">Ver novedades →</a></div><div class="product-grid"><?php foreach (array_slice($products, 0, 4) as $product) { minikids_product_card($product); } ?></div></div></section>
  <section class="section"><div class="container"><div class="promo-band"><div><span class="eyebrow">Pequeños precios, grandes momentos</span><h2>Todo por debajo de S/ 29.90</h2><p>Encuentra detalles divertidos para sorprender sin complicarte.</p><a class="button light" href="?categoria=ofertas">Ver ofertas <span>→</span></a></div><div class="promo-art" aria-hidden="true">🎈 🧸 🎁</div></div></div></section>
  <section class="section"><div class="container"><div class="newsletter"><div><h2>Recibe un poquito de magia</h2><p>Suscríbete y entérate primero de nuestras novedades y promos.</p></div><form class="newsletter-form" action="#" method="post"><input type="email" placeholder="Tu correo electrónico" aria-label="Tu correo electrónico" required><button type="submit">Suscribirme</button></form></div></div></section>
</main>
<?php get_footer(); ?>
